# Neural Network - Regression
## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

# 2. Import Data

In [2]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

## 3. Pre-processing Data

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

## 4. Split Data Into Training & Test

In [7]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [11]:
n_cols = predictors_norm.shape[1] # number of predictors

## 5. Algorithm & Optimization

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [13]:
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(50, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [14]:
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - loss: 1652.1823 - val_loss: 1149.0325 - 988ms/epoch - 43ms/step
Epoch 2/100
23/23 - 0s - loss: 1524.6431 - val_loss: 1029.9951 - 93ms/epoch - 4ms/step
Epoch 3/100
23/23 - 0s - loss: 1305.5413 - val_loss: 841.3575 - 100ms/epoch - 4ms/step
Epoch 4/100
23/23 - 0s - loss: 972.1304 - val_loss: 599.2718 - 115ms/epoch - 5ms/step
Epoch 5/100
23/23 - 0s - loss: 603.4798 - val_loss: 378.0818 - 90ms/epoch - 4ms/step
Epoch 6/100
23/23 - 0s - loss: 340.3679 - val_loss: 245.5602 - 89ms/epoch - 4ms/step
Epoch 7/100
23/23 - 0s - loss: 252.1621 - val_loss: 194.2068 - 95ms/epoch - 4ms/step
Epoch 8/100
23/23 - 0s - loss: 226.1994 - val_loss: 179.1184 - 88ms/epoch - 4ms/step
Epoch 9/100
23/23 - 0s - loss: 212.1067 - val_loss: 169.0927 - 92ms/epoch - 4ms/step
Epoch 10/100
23/23 - 0s - loss: 201.3248 - val_loss: 165.5533 - 88ms/epoch - 4ms/step
Epoch 11/100
23/23 - 0s - loss: 193.3040 - val_loss: 162.2730 - 80ms/epoch - 3ms/step
Epoch 12/100
23/23 - 0s - loss: 187.1720 - val_loss: 159.2542 - 88ms/epoch - 4ms/step
Epoch 13/100
23/23 - 0s - loss: 181.4224 - val_loss: 155.2371 - 86ms/epoch - 4ms/step
Epoch 14/100
23/23 - 0s - loss: 177.1797 - val_loss: 154.3495 - 87ms/epoch - 4ms/step
Epoch 15/100
23/23 - 0s - loss: 172.0496 - val_loss: 150.6276 - 84ms/epoch - 4ms/step
Epoch 16/100
23/23 - 0s - loss: 167.8749 - val_loss: 149.3635 - 84ms/epoch - 4ms/step
Epoch 17/100
23/23 - 0s - loss: 164.2831 - val_loss: 148.6581 - 88ms/epoch - 4ms/step
Epoch 18/100
23/23 - 0s - loss: 161.6525 - val_loss: 146.9332 - 87ms/epoch - 4ms/step
Epoch 19/100
23/23 - 0s - loss: 158.5637 - val_loss: 145.9561 - 85ms/epoch - 4ms/step
Epoch 20/100
23/23 - 0s - loss: 155.8208 - val_loss: 147.5048 - 96ms/epoch - 4ms/step
Epoch 21/100
23/23 - 0s - loss: 153.2340 - val_loss: 145.0062 - 103ms/epoch - 4ms/step
Epoch 22/100
23/23 - 0s - loss: 151.3695 - val_loss: 145.7817 - 82ms/epoch - 4ms/step
Epoch 23/100
23/23 - 0s - loss: 149.2683 - val_loss: 145.0811 - 83ms/epoch - 4ms/step
Epoch 24/100
23/23 - 0s - loss: 147.8039 - val_loss: 145.9400 - 90ms/epoch - 4ms/step
Epoch 25/100
23/23 - 0s - loss: 146.0422 - val_loss: 144.8265 - 98ms/epoch - 4ms/step
Epoch 26/100
23/23 - 0s - loss: 144.5601 - val_loss: 144.1339 - 103ms/epoch - 4ms/step
Epoch 27/100
23/23 - 0s - loss: 142.6351 - val_loss: 147.3396 - 89ms/epoch - 4ms/step
Epoch 28/100
23/23 - 0s - loss: 141.3086 - val_loss: 147.3548 - 105ms/epoch - 5ms/step
Epoch 29/100
23/23 - 0s - loss: 139.9645 - val_loss: 144.4607 - 93ms/epoch - 4ms/step
Epoch 30/100
23/23 - 0s - loss: 138.2172 - val_loss: 146.4661 - 92ms/epoch - 4ms/step
Epoch 31/100
23/23 - 0s - loss: 137.3465 - val_loss: 143.6523 - 88ms/epoch - 4ms/step
Epoch 32/100
23/23 - 0s - loss: 135.5999 - val_loss: 144.6248 - 81ms/epoch - 4ms/step
Epoch 33/100
23/23 - 0s - loss: 134.3760 - val_loss: 145.5491 - 90ms/epoch - 4ms/step
Epoch 34/100
23/23 - 0s - loss: 132.7611 - val_loss: 146.8837 - 85ms/epoch - 4ms/step
Epoch 35/100
23/23 - 0s - loss: 131.2818 - val_loss: 146.1875 - 83ms/epoch - 4ms/step
Epoch 36/100
23/23 - 0s - loss: 129.2946 - val_loss: 146.0304 - 96ms/epoch - 4ms/step
Epoch 37/100
23/23 - 0s - loss: 127.9534 - val_loss: 146.4736 - 97ms/epoch - 4ms/step
Epoch 38/100
23/23 - 0s - loss: 126.2778 - val_loss: 146.5754 - 82ms/epoch - 4ms/step
Epoch 39/100
23/23 - 0s - loss: 124.7822 - val_loss: 145.5558 - 81ms/epoch - 4ms/step
Epoch 40/100
23/23 - 0s - loss: 123.8105 - val_loss: 144.9005 - 82ms/epoch - 4ms/step
Epoch 41/100
23/23 - 0s - loss: 122.7483 - val_loss: 145.3847 - 83ms/epoch - 4ms/step
Epoch 42/100
23/23 - 0s - loss: 120.8672 - val_loss: 145.3646 - 90ms/epoch - 4ms/step
Epoch 43/100
23/23 - 0s - loss: 118.8385 - val_loss: 146.0160 - 77ms/epoch - 3ms/step
Epoch 44/100
23/23 - 0s - loss: 117.2604 - val_loss: 143.4624 - 86ms/epoch - 4ms/step
Epoch 45/100
23/23 - 0s - loss: 114.6821 - val_loss: 144.3738 - 83ms/epoch - 4ms/step
Epoch 46/100
23/23 - 0s - loss: 112.8785 - val_loss: 143.1027 - 87ms/epoch - 4ms/step
Epoch 47/100
23/23 - 0s - loss: 111.2034 - val_loss: 144.0923 - 92ms/epoch - 4ms/step
Epoch 48/100
23/23 - 0s - loss: 109.5209 - val_loss: 140.3376 - 77ms/epoch - 3ms/step
Epoch 49/100
23/23 - 0s - loss: 107.3661 - val_loss: 140.2613 - 80ms/epoch - 3ms/step
Epoch 50/100
23/23 - 0s - loss: 105.2125 - val_loss: 138.9108 - 84ms/epoch - 4ms/step
Epoch 51/100
23/23 - 0s - loss: 103.3279 - val_loss: 132.4033 - 83ms/epoch - 4ms/step
Epoch 52/100
23/23 - 0s - loss: 101.5828 - val_loss: 132.8669 - 82ms/epoch - 4ms/step
Epoch 53/100
23/23 - 0s - loss: 98.3926 - val_loss: 128.2303 - 79ms/epoch - 3ms/step
Epoch 54/100
23/23 - 0s - loss: 96.1863 - val_loss: 126.9543 - 88ms/epoch - 4ms/step
Epoch 55/100
23/23 - 0s - loss: 93.9578 - val_loss: 125.8395 - 90ms/epoch - 4ms/step
Epoch 56/100
23/23 - 0s - loss: 91.7639 - val_loss: 120.0472 - 80ms/epoch - 3ms/step
Epoch 57/100
23/23 - 0s - loss: 88.3181 - val_loss: 121.5851 - 81ms/epoch - 4ms/step
Epoch 58/100
23/23 - 0s - loss: 85.4017 - val_loss: 124.6052 - 81ms/epoch - 4ms/step
Epoch 59/100
23/23 - 0s - loss: 82.5992 - val_loss: 119.4313 - 82ms/epoch - 4ms/step
Epoch 60/100
23/23 - 0s - loss: 80.2503 - val_loss: 124.2312 - 82ms/epoch - 4ms/step
Epoch 61/100
23/23 - 0s - loss: 77.4543 - val_loss: 114.2493 - 96ms/epoch - 4ms/step
Epoch 62/100
23/23 - 0s - loss: 74.4512 - val_loss: 112.4591 - 78ms/epoch - 3ms/step
Epoch 63/100
23/23 - 0s - loss: 71.9258 - val_loss: 109.4372 - 83ms/epoch - 4ms/step
Epoch 64/100
23/23 - 0s - loss: 69.2931 - val_loss: 103.5327 - 86ms/epoch - 4ms/step
Epoch 65/100
23/23 - 0s - loss: 66.1996 - val_loss: 110.6067 - 89ms/epoch - 4ms/step
Epoch 66/100
23/23 - 0s - loss: 63.9410 - val_loss: 102.7357 - 81ms/epoch - 4ms/step
Epoch 67/100
23/23 - 0s - loss: 61.8608 - val_loss: 103.2283 - 85ms/epoch - 4ms/step
Epoch 68/100
23/23 - 0s - loss: 59.8634 - val_loss: 98.2398 - 78ms/epoch - 3ms/step
Epoch 69/100
23/23 - 0s - loss: 56.7798 - val_loss: 99.5207 - 74ms/epoch - 3ms/step
Epoch 70/100
23/23 - 0s - loss: 54.8163 - val_loss: 97.7738 - 79ms/epoch - 3ms/step
Epoch 71/100
23/23 - 0s - loss: 52.4055 - val_loss: 94.3710 - 85ms/epoch - 4ms/step
Epoch 72/100
23/23 - 0s - loss: 50.5921 - val_loss: 88.9893 - 93ms/epoch - 4ms/step
Epoch 73/100
23/23 - 0s - loss: 49.6239 - val_loss: 92.4665 - 87ms/epoch - 4ms/step
Epoch 74/100
23/23 - 0s - loss: 48.0839 - val_loss: 88.5545 - 79ms/epoch - 3ms/step
Epoch 75/100
23/23 - 0s - loss: 46.9320 - val_loss: 85.6153 - 75ms/epoch - 3ms/step
Epoch 76/100
23/23 - 0s - loss: 45.5323 - val_loss: 87.2456 - 80ms/epoch - 3ms/step
Epoch 77/100
23/23 - 0s - loss: 44.5992 - val_loss: 84.4163 - 79ms/epoch - 3ms/step
Epoch 78/100
23/23 - 0s - loss: 43.5168 - val_loss: 85.7287 - 83ms/epoch - 4ms/step
Epoch 79/100
23/23 - 0s - loss: 42.3697 - val_loss: 87.1606 - 80ms/epoch - 3ms/step
Epoch 80/100
23/23 - 0s - loss: 42.0425 - val_loss: 88.5630 - 110ms/epoch - 5ms/step
Epoch 81/100
23/23 - 0s - loss: 41.4961 - val_loss: 81.3864 - 86ms/epoch - 4ms/step
Epoch 82/100
23/23 - 0s - loss: 40.7150 - val_loss: 87.2330 - 86ms/epoch - 4ms/step
Epoch 83/100
23/23 - 0s - loss: 39.9089 - val_loss: 85.2705 - 80ms/epoch - 3ms/step
Epoch 84/100
23/23 - 0s - loss: 38.8438 - val_loss: 85.8926 - 79ms/epoch - 3ms/step
Epoch 85/100
23/23 - 0s - loss: 38.5816 - val_loss: 81.8542 - 78ms/epoch - 3ms/step
Epoch 86/100
23/23 - 0s - loss: 37.7915 - val_loss: 93.7040 - 81ms/epoch - 4ms/step
Epoch 87/100
23/23 - 0s - loss: 37.0417 - val_loss: 87.0692 - 79ms/epoch - 3ms/step
Epoch 88/100
23/23 - 0s - loss: 36.7641 - val_loss: 90.5487 - 81ms/epoch - 4ms/step
Epoch 89/100
23/23 - 0s - loss: 36.4743 - val_loss: 85.6315 - 85ms/epoch - 4ms/step
Epoch 90/100
23/23 - 0s - loss: 35.4989 - val_loss: 96.1691 - 95ms/epoch - 4ms/step
Epoch 91/100
23/23 - 0s - loss: 35.1789 - val_loss: 93.9322 - 79ms/epoch - 3ms/step
Epoch 92/100
23/23 - 0s - loss: 34.9428 - val_loss: 85.9068 - 87ms/epoch - 4ms/step
Epoch 93/100
23/23 - 0s - loss: 33.9737 - val_loss: 103.7045 - 81ms/epoch - 4ms/step
Epoch 94/100
23/23 - 0s - loss: 33.7482 - val_loss: 92.6792 - 80ms/epoch - 3ms/step
Epoch 95/100
23/23 - 0s - loss: 33.4225 - val_loss: 94.8116 - 82ms/epoch - 4ms/step
Epoch 96/100
23/23 - 0s - loss: 33.0557 - val_loss: 98.2155 - 81ms/epoch - 4ms/step
Epoch 97/100
23/23 - 0s - loss: 32.5227 - val_loss: 95.3041 - 89ms/epoch - 4ms/step
Epoch 98/100
23/23 - 0s - loss: 32.1875 - val_loss: 102.6936 - 79ms/epoch - 3ms/step
Epoch 99/100
23/23 - 0s - loss: 31.9600 - val_loss: 106.7019 - 77ms/epoch - 3ms/step
Epoch 100/100
23/23 - 0s - loss: 31.5979 - val_loss: 97.0354 - 88ms/epoch - 4ms/step